# Generated by Django 5.1.3 on 2024-11-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20241109_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
